{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red57\green57\blue57;}
{\*\expandedcolortbl;;\cssrgb\c28627\c28627\c28627;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs25\fsmilli12573 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 FROM n8nio/n8n\
}